### ISSUE TITLE
Kanban setup review

### ISSUE THREAD

**Issue by phelian23** [phelian23/react-redux-group-project#49]
We are two in the group
Here is the link to our project https://github.com/phelian23/react-redux-group-project/projects

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hello Team,  

This task is complete! Great job 🥇. There is nothing else to say other than... it's time to proceed with the next task/ project 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Board correctly setup
- Issues well created with appropriate info
- Discussion and collaboration were well observed
- Fiar distribution of tasks among team


<br>
Cheers...and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
